const base_url = 'https://app.razonet.com.br'
export const CERTIFICATES_URL = base_url + '/integration/v1/companies/company_certificate'
export const SERVICES_URL = base_url + '/integration/v1/company_services'
export const COMPANIES_URL = base_url + '/integration/v1/companies/index'
export const CUSTOMER_PORTAL_URL = 'https://www.gov.br/empresas-e-negocios/pt-br/empreendedor'